name: coctel_app
description: "App movil de recetas de Coctel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Para hacer requests HTTP
  http: ^1.2.2

  # Para traducciones automáticas
  translator: ^1.0.0

  # Para guardar favoritos
  shared_preferences: ^2.2.3

  # Dependencia para seleccionar imágenes de la galería o cámara
  image_picker: ^1.0.4

  # Para la gestión del estado del tema (modo claro/oscuro)
  provider: ^6.0.0

  # Permite encontrar rutas comunes en el sistema de archivos del dispositivo móvil
  path_provider: ^2.1.3

  # Para manipulación de rutas
  path: ^1.9.0

  # Para abrir URLs (como WhatsApp)
  url_launcher: ^6.2.6 # Puedes usar la última versión estable

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Buenas prácticas y reglas de estilo
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aquí se definen las imágenes
  assets:
    - assets/images/
